version: "3"
services:
    minecraft-store:
        container_name: minecraft-store
        build:
            context: .
            dockerfile: tools/docker/Dockerfile
        image: minecraft-store
        volumes:
          - ./logs:/app/react/logs
        ports:
          - "3000:3000"
        restart: always